# Generated by Django 3.1.7 on 2021-03-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('master', models.CharField(max_length=20, verbose_name='Master')),
                ('client', models.CharField(max_length=20, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'RecordNails',
                'verbose_name_plural': 'RecordsNails',
            },
        ),
        migrations.CreateModel(
            name='RecordsEyebrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('master', models.CharField(max_length=20, verbose_name='Master')),
                ('client', models.CharField(max_length=20, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'RecordEyebrows',
                'verbose_name_plural': 'RecordsEyebrows',
            },
        ),
        migrations.CreateModel(
            name='RecordsEyelashes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('master', models.CharField(max_length=20, verbose_name='Master')),
                ('client', models.CharField(max_length=20, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'RecordEyelashes',
                'verbose_name_plural': 'RecordsEyelashes',
            },
        ),
    ]
