# Generated by Django 3.1.7 on 2021-03-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=20, verbose_name='Client')),
                ('master', models.CharField(max_length=20, verbose_name='Master')),
                ('feedback', models.TextField(verbose_name='Feedback')),
            ],
        ),
    ]
